### PR TITLE
Evict connection

### PR DESCRIPTION
**Pull request by wqking**
Used the similar mechanism in Bitcoin to evict peers when the peers are full.

### CODE REVIEW

**Comment by meyer9** [comment]
This looks great, but I'm concerned with how it interacts with the libp2p connection manager. Can you make sure this doesn't conflict with that?

**Comment by wqking** [comment]
I checked libp2p connection manager. I don't think this conflicts with it. And even if it conflicts with it, it can be easily solved by setting higher maxPeers (or just set 0 to disable it) to libp2p connection manager.

**Comment by wqking** [comment]
BTW I didn't test the eviction, it's not easy to simulate that many connections. Maybe I should run many nodes locally to test it?

**Comment by meyer9** [comment]
I'll merge this in and then write an integration test for it. It will be good to see if integration tests work properly.

**Pull request merged**
