### PR TITLE
#49 active peer discovery

### PR DESCRIPTION
**Pull request by wqking**
I didn't test it yet.

### CODE REVIEW

**Comment by meyer9** [comment]
This doesn't work.
I ran:
```
go run cmd/beacon/synapsebeacon.go -genesistime 1557336342 -connect "/ip4/134.209.58.178/tcp/11781/ipfs/12D3KooWDW6ZvQYxhgu3i6ys6pqbwoP2YAkXJNYdcyis7nsfSSG9" -level debug
```

then,
```
go run cmd/beacon/synapsebeacon.go -genesistime 1557336342 -connect "/ip4/127.0.0.1/tcp/11781/ipfs/somethingsomethingsomething" -datadir "~/.phoresynapse1" -listen "/ip4/0.0.0.0/tcp/11881" -rpclisten "127.0.0.1:11882" -level debug -resync
```

Also, seems to be a bug with peer IDs because they always get rejected on the client.

**Comment by wqking** [comment]
Now it works.

Test,
go run cmd/beacon/synapsebeacon.go -genesistime 1557336342 -level debug

go run cmd/beacon/synapsebeacon.go -genesistime 1557336342 -datadir "/temp/phoresynapse1" -listen "/ip4/0.0.0.0/tcp/11881" -rpclisten "127.0.0.1:11882" -level debug -resync

No need to connect the nodes.

The active peer discovery needs to connect to several center servers for the routine, now the code uses the servers from libp2p example code. We may need to have our own servers?

**Comment by meyer9** [comment]
I think we can just use theirs. I wonder if there is a max connections implemented yet.

**Comment by meyer9** [comment]
Rebased with master

**Pull request merged**
