### PR TITLE
Fixed #37 Re-request epoch data after getting an error

### LINKED ISSUE #37: Re-request epoch data after getting an error
If the beacon chain lags, re-request epoch data to make sure valid block can be created.

### PR DESCRIPTION
**Pull request by wqking**

### CODE REVIEW

**Comment by meyer9** [comment]
Please rebase with master.

**Comment by wqking** [comment]
Done

**Comment by meyer9** [comment]
The errors here happen when submitting a block. If the beacon block hash is out of sync or something, submitting a block will error out. Then, we should re-request epoch data.

**Comment by wqking** [comment]
Done

**Comment by meyer9** [comment]
Sorry, I should be more clear. It should always retry.

Currently, the validator asks the beacon chain for the entire epoch of proposals/attestations and then launches goroutines that wait for the slot and propose/attest as needed.

Sometimes, after it requests the entire epoch, something is updated and the older epoch assignment becomes invalid, in which case it will error when submitting a block. If this happens, the validator should cancel all current assignments (all goroutines started) and re-request epoch data, then start the goroutines again.

**Pull request closed without merging**
